// Generated by CoffeeScript 1.9.0
(function() {
  var expect, pokemonData;

  expect = require('chai').expect;

  pokemonData = require('../lib/index');

  describe('pokemon-data', function() {
    describe('all', function() {
      it('should be an array of strings', function() {
        var isArrayOfStrings;
        isArrayOfStrings = function(array) {
          return array.every(function(item) {
            return typeof item === 'string';
          });
        };
        return expect(pokemonData.all).to.satisfy(isArrayOfStrings);
      });
      it('should contain bulbasaur', function() {
        return expect(pokemonData.all).to.include('Bulbasaur');
      });
      return it('should contain 721 pokemons', function() {
        return expect(pokemonData.all).to.have.length(721);
      });
    });
    describe('random', function() {
      it('should be a string', function() {
        var isString;
        isString = function(item) {
          return typeof item === 'string';
        };
        return expect(pokemonData.random()).to.satisfy(isString);
      });
      it('should be contained in contain all', function() {
        var randomItem;
        randomItem = pokemonData.random();
        return expect(pokemonData.all).to.include(randomItem);
      });
      return it('should work with getRandom', function() {
        var randomItem;
        randomItem = pokemonData.getRandom();
        return expect(pokemonData.all).to.include(randomItem);
      });
    });
    return describe('getById', function() {
      return it('should return pikachu for id 25', function() {
        return expect(pokemonData.getById(25)).to.equal('Pikachu');
      });
    });
  });

}).call(this);
