// Generated by CoffeeScript 1.9.0
(function() {
  var pokemonData, uniqueRandomArray;

  uniqueRandomArray = require('unique-random-array');

  pokemonData = require('./pokemon-data.json');

  module.exports = {
    all: pokemonData,
    getRandom: uniqueRandomArray(pokemonData),
    random: function() {
      return this.getRandom();
    },
    getById: function(id) {
      return this.all[id - 1];
    }
  };

}).call(this);
