// Generated by CoffeeScript 1.9.0
(function() {
  var pokemonData, uniqueRandomArray;

  uniqueRandomArray = require('unique-random-array');

  pokemonData = require('./pokemon-data.json');

  module.exports = {
    all: pokemonData,
    random: uniqueRandomArray(pokemonData)
  };

}).call(this);
